### ISSUE TITLE
Why Assertion failed: rc != -1 ?

### ISSUE THREAD

**Issue by zhq0918** [cloud-security-research/sgx-ra-tls#13]
I want to run the https server,and I executed the command :
make -C sgxlkl run-https-server
the information is :
make: Entering directory '/opt/sgx_main/ai_security_lkl/sgx-ra-tls/sgxlkl'
LD_PRELOAD=/ldpreload.so SGXLKL_TAP=sgxlkl_tap0 RATLS_AESMD_IP=10.0.1.254 SGXLKL_HEAP=268435456 SGXLKL_KEY=/opt/sgx_main/ai_security_lkl/sgx-ra-tls/sgxlkl/sgx-lkl/build/config/enclave_debug.key sgx-lkl/build/sgx-lkl-run sgx-lkl/apps/https-server/sgxlkl-miniroot-fs.img /usr/bin/python /https-server.py
**ERROR: ld.so: object '/ldpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.**
**Assertion failed: rc != -1** (../nonsdk-ra-attester.c: open_socket: 262)
Segmentation fault (core dumped)
Makefile:118: recipe for target 'run-https-server' failed
make: *** [run-https-server] Error 139
make: Leaving directory '/opt/sgx_main/ai_security_lkl/sgx-ra-tls/sgxlkl'

Why?

**Comment by thomasknauth** [comment]
Did you set up the network with `EXTERNAL_IFACE=eth0 make -C sgxlkl up-sgxlkl-network` before issuing the run-https-server target?

**Comment by zhq0918** [comment]
@thomasknauth thanks，I tried it , and I resolved the problem.

**Comment by kanakraju73** [comment]
I'm getting exactly the same error while running **run-https-server** and **run-wolfssl-server** [examples](https://github.com/cloud-security-research/sgx-ra-tls#sgx-lkl) with SGX-LKL.

I did run the ```EXTERNAL_IFACE=eth0 make -C sgxlkl up-sgxlkl-network``` before running the examples. 


The last few lines of https-server reads:

```make[2]: Leaving directory '/home/bhamidi/clones/sgx-ra-tls/sgxlkl/sgx-lkl/src'
make[1]: Leaving directory '/home/bhamidi/clones/sgx-ra-tls/sgxlkl/sgx-lkl'
LD_PRELOAD=/ldpreload.so SGXLKL_TAP=sgxlkl_tap0 RATLS_AESMD_IP=10.0.1.254 SGXLKL_HEAP=268435456 SGXLKL_KEY=/home/bhamidi/clones/sgx-ra-tls/sgxlkl/sgx-lkl/build/config/enclave_debug.key sgx-lkl/build/sgx-lkl-run sgx-lkl/apps/https-server/sgxlkl-miniroot-fs.img /usr/bin/python /https-server.py
Makefile:118: recipe for target 'run-https-server' failed
make: Leaving directory '/home/bhamidi/clones/sgx-ra-tls/sgxlkl'
Assertion failed: rc != -1 (../nonsdk-ra-attester.c: open_socket: 262)
Segmentation fault
make: *** [run-https-server] Error 139
```

The detailed logs for both the example are attached.
[run-wolfssl-server](https://github.com/cloud-security-research/sgx-ra-tls/files/4155959/output.txt)
[run-https-server](https://github.com/cloud-security-research/sgx-ra-tls/files/4155960/output2.txt)

Note: I'm able to run SGX-SDK and graphene examples without any problems.

Where am I going wrong?
