### ISSUE TITLE
Why curl_easy_perform= 5 ?

### ISSUE THREAD

**Issue by zhq0918** [cloud-security-research/sgx-ra-tls#14]
when run "make -C sgxlkl run-https-server", I met the error "curl_easy_perform = 5",I checked it , and it means that "CURLE_COULDNT_RESOLVE_PROXY",but I run "./App -s" no problem,how can i resolve this problem? thanks.

**Comment by dimakuv** [comment]
Did you check this: https://github.com/cloud-security-research/sgx-ra-tls/issues/2 ?

Curl and AESMD (the daemon which forwards RA requests) need accurate proxy settings.
