### ISSUE TITLE
what's the relation between enc_wolfSSL_read and ocall_send?

### ISSUE THREAD

**Issue by zhq0918** [cloud-security-research/sgx-ra-tls#16]
when i debuged the demo,I found when the demo execute the function which named enc_wolfSSL_read in server-tls.c , the demo called the function ocall_send which in App.c.I want to know what's the relation between enc_wolfSSL_read and ocall_send?thanks.

**Comment by thomasknauth** [comment]
Can you provide a stack trace? Is the question why a call to (enc_wolfSSL_)read may also (ocall_)send data? Maybe the TLS session was not established yet. Before the application can actually read data, the TLS library needs to set up connection. The TLS handshake requires bi-directional communication, hence you might also see sends even though the application initially only wanted to read.

**Comment by zhq0918** [comment]
Thank you @thomasknauth ,  I tracked them again and found that they had nothing to do with each other, but I didn't know when would trigger the ocall_send and ocall_recv function.
