### ISSUE TITLE
About enc_wolfSSL_CTX_load_verify_buffer?

### ISSUE THREAD

**Issue by zhq0918** [cloud-security-research/sgx-ra-tls#18]
I tested the project sgx-ra-tls/deps/wolfssl-examples/SGX_Linux, I want use the function which name enc_wolfSSL_CTX_load_verify_buffer, its return value is -150,i checkd the info is: ASN date error, current date before.The same method I test wolfSSL_CTX_load_verify_buffer  outer enclave , it reurn ssl_success,why?

**Comment by zhq0918** [comment]
Ｉ traced the code,and i found that ,the reason that enc_wolfSSL_CTX_load_verify_buffer returned value is -150 is the XTIME in wolfssl-ra-attester.c like this:
#ifdef WOLFSSL_SGX

time_t XTIME(time_t* tloc) {
    //printf("wolfssl-ra-attester.c...XTIME...\n");
    time_t x = 1512498557; /* Dec 5, 2017, 10:29 PDT */ Is the x the current time stamp?
    if (tloc) *tloc = x;
    return x;
}

time_t mktime(struct tm* tm) {
    (void) tm;
    assert(0);
    return (time_t) 0;
}
#endif

**Comment by thomasknauth** [comment]
Why are you actually using enc_wolfSSL_CTX_load_verify_buffer()? [Looking at the wolfSSL source, this function is for loading CA certificates](https://github.com/wolfSSL/wolfssl/blob/f114932a0363a53053c6e903b431a2eda9b95da5/src/ssl.c#L11234). The certificate that RA-TLS generates is *not* a CA certificate. I am guessing that enc_wolfSSL_CTX_load_verify_buffer() tries to do some sanity checks on the certificate related to its validity period and this fails.

I'd say calling enc_wolfSSL_CTX_load_verify_buffer() within the scope of what the example is trying to demonstrate is not supported/intended. You may want to look at what exactly enc_wolfSSL_CTX_load_verify_buffer() verifies and where it obtains its time from, if you still want to pursue this route.
