### ISSUE TITLE
Docker build succeeded but running App -s failed

### ISSUE THREAD

**Issue by Ruide** [cloud-security-research/sgx-ra-tls#20]
Hi Sir/Madam,

I follow the docker build for sgxsdk, and all the compilation succeeded. However, it is giving me 
Assertion `sig_begin != NULL' failed. After investigation, i find out the problem is with curl with IAS server. It is /* 58 - problem with the local certificate */. I can use that certificate with the other remote attestation sample provided by Intel. https://github.com/intel/sgx-ra-sample. 

I am receiving the following warning. Is there any plan on update this project according to the API change?

warning: 299 test-as.sgx.trustedservices.intel.com "The version of Attestation Service for Intel(R) Software Guard Extensions API you are using has reached end of life and is no longer available. For details on how to update to the latest version of the API, please refer to the IAS API spec [located here: https://software.intel.com/sites/default/files/managed/7e/3b/ias-api-spec.pdf]."

Turns out I can change /sgx-ra-tls/ias-ra.c v2 to v3 to the following and communicate with IAS server!
ret = snprintf(url, sizeof(url), "https://%s/attestation/sgx/v3/report",

Thanks!
Rd

**Comment by thomasknauth** [comment]
Our internal version has this fix already. We plan to update the public repository soon. Sorry for the confusion.
